---
title: "Plotly Example"
author: "Lucas Qualmann"
date: "10/11/2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Histogram of MPG Rates
```{r, message = FALSE}
library(plotly)
plot_ly(x = mtcars$mpg, type = "histogram") %>% 
        layout(title = "MPG Rates in Mtcars Dataset",
               xaxis = list(title = "MPG"),
               yaxis = list(title = "# of occurences"))
```

## R Code for Previous Slide

```{r, eval = FALSE, echo = TRUE}
library(plotly)
plot_ly(x = mtcars$mpg, type = "histogram") %>% 
        layout(title = "MPG Rates in Mtcars Dataset",
               xaxis = list(title = "MPG"),
               yaxis = list(title = "# of occurences"))
```

## Scatterplot of MPG vs Variables
```{r, message = FALSE, warning=FALSE}
library(plotly)
plot_ly(x = mtcars$hp, y = mtcars$mpg, mode = "markers",
        size = mtcars$wt, color = as.factor(mtcars$cyl),
        text = paste("Weight: ", mtcars$wt)) %>% 
        layout(title = "MPG Rates vs Horsepower, Cylinders, and Weight",
               xaxis = list(title = "Horsepower"),
               yaxis = list(title = "MPG"))
```

## R Code for Previous Slide

```{r, eval = FALSE, echo = TRUE}
library(plotly)
plot_ly(x = mtcars$hp, y = mtcars$mpg, mode = "markers",
        size = mtcars$wt, color = as.factor(mtcars$cyl),
        text = paste("Weight: ", mtcars$wt)) %>% 
        layout(title = "MPG Rates vs Horsepower, Cylinders, and Weight",
               xaxis = list(title = "Horsepower"),
               yaxis = list(title = "MPG"))
```


